"""
This type stub file was generated by pyright.
"""

def extract_date(html): # -> None:
    """Return the article date from the article HTML"""
    ...

def ensure_iso_date_format(date_string, ignoretz=...):
    """Check date_string is in one of our supported formats and return it"""
    ...

