"""
This type stub file was generated by pyright.
"""

def extract_title(html):  # -> None:
    """Return the article title from the article HTML"""
    ...

def combine_similar_titles(extracted_strings):
    """Take a dictionary with titles and nested dicts with scores and combine scores for titles which we decide are the same."""
    ...
