"""
This type stub file was generated by pyright.
"""

def extract_element(
    html, xpaths, process_dict_fn=...
):  # -> defaultdict[Any, dict[Any, Any]] | None:
    """Return the relevant elements (titles, dates or bylines) from article HTML, specified by xpaths.
    xpaths should be a list of tuples, each with the xpath and a reliability scores.
    Processing of the dictionary can be handled with the arg function.
    The returned dictionary should have the processed elements as keys and dicts with scores and the xpaths used as values
    """
    ...
