"""
This type stub file was generated by pyright.
"""

from typing import TypedDict

type PlainTextItem = str | list[PlainTextItem]
type PlainText = list[PlainTextItem]

class simple_json_from_html_string_Output(TypedDict):
    title: str | None
    """The article title"""
    byline: str | None
    """Author information"""
    content: str | None
    """A simplified HTML representation of the article, with all article text contained
    in paragraph elements."""
    plain_content: str | None
    """A "plain" version of the simplified Readability.js article HTML present in the
    content field. This attempts to retain only the plain text content of the article,
    while preserving the HTML structure."""
    plain_text: PlainText | None
    """A list containing plain text representations of each paragraph (<p>) or list
    (<ol> or <ul>) present in the simplified Readability.js article HTML in the content
    field. Each paragraph or list is represented as a single string. List strings look
    like "* item 1, * item 2, * item 3," for both ordered and unordered lists (note the
    trailing ,)."""

def have_node():  # -> bool:
    """Check that we can run node and have a new enough version"""
    ...

def simple_json_from_html_string(
    html: str, content_digests=..., node_indexes=..., use_readability: bool = ...
) -> simple_json_from_html_string_Output: ...
def extract_text_blocks_as_plain_text(
    paragraph_html,
):  # -> list[dict[str, Any | str | None] | dict[str, str | None]]:
    ...
def plain_text_leaf_node(
    element,
):  # -> dict[str, Any | str | None] | dict[str, str | None]:
    ...
def plain_content(readability_content, content_digests, node_indexes):  # -> str:
    ...
def plain_elements(elements, content_digests, node_indexes):  # -> list[Any]:
    ...
def plain_element(element, content_digests, node_indexes):  # -> Any:
    ...
def is_leaf(element):  # -> bool:
    ...
def is_text(element):  # -> bool:
    ...
def is_non_printing(element):  # -> bool:
    ...
def add_node_indexes(element, node_index=...): ...
def add_content_digest(element): ...
def content_digest(element): ...
