"""
This type stub file was generated by pyright.
"""

"""Turn input HTML into a cleaned parsed tree."""
def simple_tree_from_html_string(html): # -> BeautifulSoup | Tag:
    """Turn input HTML into a cleaned parsed tree."""
    ...

