"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

"""Utility functions

"""

@contextmanager
def chdir(path):  # -> Generator[None, Any, None]:
    """Change directory in context and return to original on exit"""
    ...
