"""
This type stub file was generated by pyright.
"""

"""Common HTML cleaning functions."""

def elements_to_delete():  # -> list[str]:
    """Elements that will be deleted together with their contents."""
    ...

def elements_to_replace_with_contents():  # -> list[str]:
    """Elements that we will discard while keeping their contents."""
    ...

def special_elements():  # -> list[str]:
    """Elements that we will discard while keeping their contents that need
    additional processing."""
    ...

def block_level_whitelist():  # -> list[str]:
    """Elements that we will always accept."""
    ...

def structural_elements():  # -> list[str]:
    """Structural elements we do no further processing on (though we do remove attributes and alter their contents)"""
    ...

def metadata_elements():  # -> list[str]:
    """Metadata elements we do no further processing on (though we do remove attributes and alter their contents)"""
    ...

def linebreak_elements():  # -> list[str]:
    ...
def known_elements():  # -> list[str]:
    """All elements that we know by name."""
    ...

def remove_metadata(soup):  # -> None:
    """Remove comments, CData and doctype. These are not rendered by browsers.
    The lxml-based parsers automatically convert CData to comments unless it is
    inside <script> tags. CData will therefore be removed either as a comment
    or as part of a <script> but if any other behaviour is desired, the HTML
    will need to be pre-processed before giving it to the BeautifulSoup parser.

    We were a bit worried about potentially removing content here but satisfied
    ourselves it won't be displayed by most browsers in most cases
    (see https://github.com/alan-turing-institute/ReadabiliPy/issues/32)"""
    ...

def strip_attributes(soup):  # -> None:
    """Strip class and style attributes."""
    ...

def remove_blacklist(soup):  # -> None:
    """Remove all blacklisted elements."""
    ...

def unwrap_elements(soup):  # -> None:
    """Flatten all elements where we are only interested in their contents."""
    ...

def process_special_elements(soup):  # -> None:
    """Flatten special elements while processing their contents."""
    ...

def process_unknown_elements(soup):  # -> None:
    """Replace any unknown elements with their contents."""
    ...

def consolidate_text(soup):  # -> None:
    """Join any consecutive NavigableStrings together."""
    ...

def remove_empty_strings_and_elements(soup):  # -> None:
    """Remove any strings which contain only whitespace. Without this,
    consecutive linebreaks may not be identified correctly."""
    ...

def unnest_paragraphs(soup):  # -> None:
    """Split out block-level elements illegally contained inside paragraphs."""
    ...

def insert_paragraph_breaks(soup):  # -> None:
    """Identify <br> and <hr> and split their parent element into multiple elements where appropriate."""
    ...

def normalise_strings(soup):  # -> None:
    """Remove extraneous whitespace and fix unicode issues in all strings."""
    ...

def wrap_bare_text(soup):  # -> None:
    """Wrap any remaining bare text in <p> tags.

    We do this to ensure that there is a strong, unique correspondance between presentational paragraphs and DOM structure
     - all presentational paragraphs should be the only content associated with their immediate parent
     - all presentational paragraphs at the same conceptual level should be equally nested
     - the string as displayed in the browser should be equivalent to the innerHTML of the parent (so that indexing is equivalent between presentation and source)

    The following examples should not be allowed:

     1. Two presentational elements at the same DOM level have non-equivalent index levels
       <div index="1.1">
         text
         <p index="1.1.1">more text</p>
       </div>

     2. Index 1.1 might contain both strings
       <div index="1.1">
         <p index="1.1.1">more text</p>
         text
       </div>

     3. Two presentational paragraphs are included in the same index
       <div index="1.1">
         text
         <p index="1.1.1">more text</p>
         yet more text
       </div>
    """
    ...

def recursively_prune_elements(soup):  # -> None:
    """Recursively prune out any elements which have no children or only zero-length children."""
    ...
