"""
This type stub file was generated by pyright.
"""

"""Common text manipulation functions."""
matched_punctuation_marks = ...
terminal_punctuation_marks = ...
def normalise_unicode(text): # -> str:
    """Normalise unicode such that things that are visually equivalent map to the same unicode string where possible."""
    ...

def normalise_whitespace(text): # -> str:
    """Replace runs of whitespace characters with a single space as this is what happens when HTML text is displayed."""
    ...

def normalise_text(text): # -> str:
    """Normalise unicode and whitespace."""
    ...

def strip_html_whitespace(text): # -> str:
    """Simplify HTML by stripping whitespace."""
    ...

def strip_control_characters(text): # -> LiteralString:
    """Strip out unicode control characters which might break the parsing."""
    ...

